import { Providers } from "@/components/Providers";
import "./globals.css";
import localFont from "next/font/local";
import { getSessionUser } from "@/lib/helpers/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const poppins = localFont({
  variable: "font-poppins",
  src: "../fonts/Poppins/Poppins-Regular.ttf",
});

export default async function RootLayout({ children }) {
  const user = await getSessionUser();

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {/* <div>Failed!!</div> */}
        <Providers user={user}>{children}</Providers>
      </body>
    </html>
  );
}
