import { Providers } from "@/components/Providers";
import "./globals.css";
import localFont from 'next/font/local';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const poppins = localFont({
    variable: 'font-poppins',
    src: '../fonts/Poppins/Poppins-Regular.ttf',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {/* <div>Failed!!</div> */}
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
