const PUBLIC_CONTACT_PHONE_E164 = "+971507263306";
const PUBLIC_CONTACT_PHONE_DISPLAY = "+971 50 726 3306";
const PUBLIC_CONTACT_PHONE_DIGITS = PUBLIC_CONTACT_PHONE_E164.replace(
  /\D/g,
  "",
);

const PUBLIC_CONTACT = {
  phoneE164: PUBLIC_CONTACT_PHONE_E164,
  phoneDisplay: PUBLIC_CONTACT_PHONE_DISPLAY,
  telLink: `tel:${PUBLIC_CONTACT_PHONE_E164}`,
  whatsappLink: `https://wa.me/${PUBLIC_CONTACT_PHONE_DIGITS}`,
};

export { PUBLIC_CONTACT };
